# Generated by Django 3.2.3 on 2021-06-01 00:11

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_manufacturer', models.CharField(max_length=20, verbose_name='Manufacturer')),
                ('car_model', models.CharField(max_length=40, unique=True, verbose_name='Model')),
                ('car_from', models.DateField(verbose_name='From')),
                ('car_to', models.DateField(verbose_name='To')),
                ('transmission', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_l', models.CharField(max_length=10, verbose_name='Litre')),
                ('engine_ide', models.CharField(max_length=15, verbose_name='Code')),
                ('engine_type', models.CharField(max_length=15, verbose_name='Type')),
                ('engine_cylinder', models.IntegerField(verbose_name='Cylinder (ccm)')),
                ('engine_pistons', models.IntegerField(verbose_name='Pistons')),
                ('engine_power_kw', models.IntegerField(verbose_name='Power (kW)')),
                ('engine_power_hp', models.IntegerField(verbose_name='Power (hp)')),
                ('car_engine_info', models.ManyToManyField(to='spareapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_photo', models.ImageField(upload_to='spares')),
                ('spare_code', models.CharField(max_length=15, unique=True, verbose_name='Code')),
                ('spare_brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('spare_name', models.CharField(max_length=20, verbose_name='Name')),
                ('shape', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shape')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Long')),
                ('wide', models.FloatField(blank=True, null=True, verbose_name='Wide')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='High')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='Diameter')),
                ('radio', models.FloatField(blank=True, null=True, verbose_name='Radio')),
                ('car_info', models.ManyToManyField(blank=True, null=True, to='spareapp.car')),
                ('engine_info', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='car_info', chained_model_field='engine_ide', null=True, to='spareapp.engine')),
                ('spare_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareapp.category')),
                ('spare_depend', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='spare_category', chained_model_field='spare_code', null=True, related_name='_spareapp_spare_spare_depend_+', to='spareapp.spare')),
            ],
        ),
    ]
