# Generated by Django 3.2.3 on 2021-06-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='spare_depend',
        ),
        migrations.AlterField(
            model_name='spare',
            name='car_info',
            field=models.ManyToManyField(to='spareapp.car'),
        ),
    ]
