# Generated by Django 3.2.3 on 2021-06-01 00:38

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0002_auto_20210531_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='car_info', chained_model_field='engine_ide', to='spareapp.engine'),
        ),
    ]
