# Generated by Django 3.2.3 on 2021-06-01 00:40

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0003_alter_spare_engine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='car_info', chained_model_field='engine_ide', to='spareapp.engine', verbose_name='engineinfo'),
        ),
    ]
