# Generated by Django 3.2.3 on 2021-06-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0005_alter_spare_engine_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='high',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='long',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_brand',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_category',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_code',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_name',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_photo',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='wide',
        ),
    ]
