# Generated by Django 3.2.3 on 2021-06-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0006_auto_20210531_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='radio',
            field=models.FloatField(blank=True, null=True, verbose_name='Radio'),
        ),
    ]
