# Generated by Django 3.2.3 on 2021-06-01 01:16

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0007_spare_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publications', models.ManyToManyField(to='spareapp.Publication')),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.RemoveField(
            model_name='engine',
            name='car_engine_info',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='car_info',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='engine_info',
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='engine',
        ),
        migrations.DeleteModel(
            name='spare',
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ManyToManyField(to='spareapp.Publication'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='publication', chained_model_field='publications', to='spareapp.Writer', verbose_name='writer'),
        ),
    ]
