# Generated by Django 3.2.3 on 2021-06-01 01:35

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0010_alter_spare_engine_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_manufacturer',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_ide',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_l',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_pistons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_kw',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='car_info', chained_model_field='engine_ide', to='spareapp.engine'),
        ),
    ]
