# Generated by Django 3.2.3 on 2021-06-01 01:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0011_auto_20210531_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='spare_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category'),
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_depend',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='spare_category', chained_model_field='spare_depend', null=True, related_name='_spareapp_spare_spare_depend_+', to='spareapp.spare'),
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_photo',
            field=models.ImageField(null=True, upload_to='spares', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_from',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_manufacturer',
            field=models.CharField(max_length=20, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=40, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_to',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(verbose_name='Cylinder (ccm)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_ide',
            field=models.CharField(max_length=15, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_l',
            field=models.CharField(max_length=10, verbose_name='Litre'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_pistons',
            field=models.IntegerField(verbose_name='Pistons'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_hp',
            field=models.IntegerField(verbose_name='Power (hp)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_kw',
            field=models.IntegerField(verbose_name='Power (kW)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='car_info',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.car'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='car_info', chained_model_field='car_engine_info', null=True, to='spareapp.engine'),
        ),
    ]
