# Generated by Django 3.2.3 on 2021-06-01 02:03

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0012_auto_20210531_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='spare_spare',
            field=models.ManyToManyField(blank=True, null=True, related_name='_spareapp_spare_spare_spare_+', to='spareapp.spare'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_depend',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='spare_spare', chained_model_field='spare_depend', null=True, related_name='_spareapp_spare_spare_depend_+', to='spareapp.spare'),
        ),
    ]
