# Generated by Django 3.2.3 on 2021-06-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0014_remove_spare_spare_depend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_photo',
            field=models.ImageField(blank=True, null=True, upload_to='spares', verbose_name='Photo'),
        ),
    ]
