# Generated by Django 3.2.3 on 2021-06-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0015_alter_spare_spare_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=100, unique=True, verbose_name='Model'),
        ),
    ]
