# Generated by Django 3.2.3 on 2021-06-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0017_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_ide',
            field=models.CharField(max_length=80, verbose_name='Code'),
        ),
    ]
