# Generated by Django 3.2.3 on 2021-06-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0020_auto_20210601_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
