# Generated by Django 3.2.3 on 2021-06-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0021_alter_spare_spare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_from',
            field=models.DateField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_manufacturer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_to',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='car_engine_info',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.car'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cylinder (ccm)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_ide',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_l',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Litre'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_pistons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pistons'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power (hp)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power_kw',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power (kW)'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Name'),
        ),
    ]
