# Generated by Django 3.2.3 on 2021-06-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0022_auto_20210604_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=80, null=True, verbose_name='Code')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category'),
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_reference',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.reference'),
        ),
    ]
