# Generated by Django 3.2.4 on 2021-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0028_auto_20210617_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carfrom',
            field=models.IntegerField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='car',
            name='carto',
            field=models.IntegerField(blank=True, null=True, verbose_name='To'),
        ),
    ]
