# Generated by Django 3.2.4 on 2021-06-18 18:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0029_auto_20210617_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributeName', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('atributeVal', models.FloatField(blank=True, null=True, verbose_name='Atribute')),
                ('dimensionCar', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='dimensionSpare', chained_model_field='car_manufacturer', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car')),
                ('dimensionSpare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare')),
            ],
        ),
    ]
