# Generated by Django 3.2.4 on 2021-06-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0030_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='dimensionCar',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='dimensionSpare',
        ),
    ]
