# Generated by Django 3.2.4 on 2021-06-18 20:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0036_remove_dimension_dimensioncar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='dimensionCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimensionSpare',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='dimensionCategory', chained_model_field='spare_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare'),
        ),
    ]
