# Generated by Django 3.2.4 on 2021-06-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0037_auto_20210618_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='high',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='long',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='radio',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='wide',
        ),
    ]
