# Generated by Django 3.2.4 on 2021-06-19 18:23

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0038_auto_20210619_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='atribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributeName', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('atributeVal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Atribute')),
                ('atributeCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category')),
                ('atributeSpare', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='atributeCategory', chained_model_field='spare_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare')),
            ],
        ),
    ]
