# Generated by Django 3.2.4 on 2021-06-21 19:41

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0039_atribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='reference_car',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceCar',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='referenceSpare', chained_model_field='car_manufacturer', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Spare'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceSpare',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='atributeCategory', chained_model_field='spare_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare'),
        ),
    ]
