# Generated by Django 3.2.4 on 2021-06-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0041_alter_reference_referencespare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
