# Generated by Django 3.2.4 on 2021-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0043_alter_reference_referencecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='shape',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Shape'),
        ),
    ]
