# Generated by Django 3.2.4 on 2021-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0044_alter_spare_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='shape',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shape'),
        ),
    ]
