# Generated by Django 3.2.4 on 2021-06-21 23:33

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0052_alter_reference_referencecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='referenceCar',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='referenceSpare', chained_model_field='car_info', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='spareapp.spare', verbose_name='Car'),
        ),
    ]
