# Generated by Django 3.2.4 on 2021-06-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0057_alter_reference_referencespare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='referenceCar',
            field=models.ForeignKey(blank=True, limit_choices_to={'car_manufacturer': 'referenceSpare__car_info__car_manufacturer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Car'),
        ),
    ]
