# Generated by Django 3.2.4 on 2021-06-22 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0071_alter_reference_referencecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='referenceCar',
            field=models.ForeignKey(blank=True, limit_choices_to={'spare': ()}, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Car'),
        ),
    ]
