# Generated by Django 3.2.4 on 2021-06-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0079_auto_20210622_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='spare_reference',
        ),
    ]
