# Generated by Django 3.2.4 on 2021-06-22 18:32

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0080_remove_spare_spare_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='referenceCar',
            field=models.ForeignKey(blank=True, limit_choices_to={'spare__id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Car'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referenceSpare',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='referenceCategory', chained_model_field='spare_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='referenceCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
    ]
