# Generated by Django 3.2.4 on 2021-07-09 19:15

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0086_alter_reference_referencecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='referenceCar',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='referenceSpare', chained_model_field='car_manufacturer', limit_choices_to={'spare__id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Car'),
        ),
    ]
