# Generated by Django 3.2.4 on 2021-07-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0088_auto_20210709_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimension',
            name='dimensionCategory',
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimensionSpare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare'),
        ),
    ]
