# Generated by Django 3.2.4 on 2021-07-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0089_auto_20210709_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='referenceCategory',
        ),
        migrations.AlterField(
            model_name='reference',
            name='referenceCar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.car', verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='referenceSpare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare'),
        ),
    ]
