# Generated by Django 3.2.4 on 2021-07-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0090_auto_20210709_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='price_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Price D'),
        ),
        migrations.AddField(
            model_name='spare',
            name='price_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Price M'),
        ),
    ]
