# Generated by Django 3.2.4 on 2021-07-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0091_auto_20210709_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='referenceCar',
        ),
    ]
