# Generated by Django 3.2.4 on 2021-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0092_remove_reference_referencecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Chasis'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='atributeVal',
            field=models.FloatField(blank=True, null=True, verbose_name='Atribute (mm)'),
        ),
    ]
