# Generated by Django 3.2.4 on 2021-07-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0095_alter_dimension_dimensionspare'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(blank=True, max_length=40, null=True, verbose_name='Vendor name')),
            ],
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_vendor',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.vendor', verbose_name='Vendor'),
        ),
    ]
