# Generated by Django 3.2.4 on 2021-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0096_auto_20210711_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Description'),
        ),
    ]
