# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0097_alter_spare_spare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_cylinder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valve'),
        ),
    ]
