# Generated by Django 3.2.4 on 2021-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0101_sparecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparecart',
            name='nameUser',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sparecart',
            name='spareCode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
    ]
