# Generated by Django 3.2.4 on 2021-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0102_auto_20210902_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparecart',
            name='spareId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id'),
        ),
    ]
