# Generated by Django 3.2.4 on 2021-09-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0105_auto_20210909_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
