# Generated by Django 3.2.4 on 2021-09-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0113_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
