# Generated by Django 3.2.4 on 2021-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0117_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='bodega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='detal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mayorista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ventas',
            field=models.BooleanField(default=False),
        ),
    ]
