# Generated by Django 3.2.4 on 2021-09-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0118_auto_20210909_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='detal',
            field=models.BooleanField(default=True),
        ),
    ]
