# Generated by Django 3.2.4 on 2021-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0119_alter_profile_detal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoría')),
                ('fechaCreado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('fechaTope', models.DateField(blank=True, null=True, verbose_name='Fecha tope')),
                ('ingreso', models.BooleanField(default=True, verbose_name='Ingreso')),
                ('egreso', models.BooleanField(default=False, verbose_name='Egreso')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='Número de factura')),
                ('iva', models.FloatField(blank=True, null=True, verbose_name='Impuesto')),
                ('monto', models.FloatField(blank=True, null=True, verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo')),
            ],
        ),
    ]
