# Generated by Django 3.2.4 on 2021-09-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0120_factcategory_factura_persona_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type',
            new_name='factType',
        ),
    ]
