# Generated by Django 3.2.4 on 2021-09-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0124_alter_factcategory_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='refCategory',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='refPersona',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='refType',
        ),
        migrations.DeleteModel(
            name='factCategory',
        ),
        migrations.DeleteModel(
            name='factType',
        ),
        migrations.DeleteModel(
            name='factura',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
