# Generated by Django 3.2.4 on 2021-09-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0125_auto_20210915_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='factCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoría')),
                ('ingreso', models.BooleanField(default=False, verbose_name='Ingreso')),
                ('egreso', models.BooleanField(default=False, verbose_name='Egreso')),
                ('limite', models.BooleanField(default=False, verbose_name='Fecha imite')),
            ],
        ),
        migrations.CreateModel(
            name='factType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tipo', max_length=20, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='Número de factura')),
                ('fechaCreado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('fechaTope', models.DateField(blank=True, null=True, verbose_name='Fecha tope')),
                ('iva', models.FloatField(blank=True, null=True, verbose_name='Impuesto')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('refCategory', models.ForeignKey(default='Categoria', on_delete=django.db.models.deletion.CASCADE, to='spareapp.factcategory', verbose_name='Category')),
                ('refPersona', models.ForeignKey(default='Persona', on_delete=django.db.models.deletion.CASCADE, to='spareapp.persona', verbose_name='Persona')),
                ('refType', models.ForeignKey(default='Tipo', on_delete=django.db.models.deletion.CASCADE, to='spareapp.facttype', verbose_name='Tipo')),
            ],
        ),
    ]
