# Generated by Django 3.2.4 on 2021-09-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0126_factcategory_facttype_factura_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tabStart', models.FloatField(verbose_name='Start')),
                ('tabPagos', models.FloatField(verbose_name='Pagos')),
                ('tabRetiros', models.FloatField(verbose_name='Retiros')),
                ('tabTotal', models.FloatField(verbose_name='Total')),
                ('tabTipo', models.ForeignKey(default='Tipo', on_delete=django.db.models.deletion.CASCADE, to='spareapp.facttype', verbose_name='Tipo')),
            ],
        ),
    ]
