# Generated by Django 3.2.4 on 2021-09-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0128_maintableaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='tabStart',
        ),
        migrations.RemoveField(
            model_name='maintableaux',
            name='tabStart',
        ),
    ]
