# Generated by Django 3.2.4 on 2021-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0129_auto_20210921_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pendiente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pendiente'),
        ),
    ]
