# Generated by Django 3.2.4 on 2021-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0131_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='documento',
            field=models.CharField(default='', max_length=20, verbose_name='Documento'),
        ),
    ]
