# Generated by Django 3.2.4 on 2021-09-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0133_auto_20210924_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttype',
            name='manual',
            field=models.BooleanField(default=True, verbose_name='Manual'),
        ),
    ]
