# Generated by Django 3.2.4 on 2021-09-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0134_facttype_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttype',
            name='include',
            field=models.BooleanField(default=True, verbose_name='Include'),
        ),
    ]
