# Generated by Django 3.2.4 on 2021-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0136_auto_20210927_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fechaCobrado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha cobrado'),
        ),
    ]
