# Generated by Django 3.2.4 on 2021-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0138_alter_persona_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de factura'),
        ),
    ]
