# Generated by Django 3.2.4 on 2021-10-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0140_auto_20211017_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='note',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Nota'),
        ),
    ]
