# Generated by Django 3.2.4 on 2021-11-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0141_factura_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facttype',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='Manual'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaCreado',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
