# Generated by Django 3.2.4 on 2021-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0142_auto_20211107_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttype',
            name='MercPagada',
            field=models.BooleanField(default=False, verbose_name='Mercancia pagada'),
        ),
        migrations.AddField(
            model_name='facttype',
            name='MercPagar',
            field=models.BooleanField(default=False, verbose_name='Mercancia pagada'),
        ),
        migrations.AddField(
            model_name='facttype',
            name='facCobrada',
            field=models.BooleanField(default=False, verbose_name='Factura cobrada'),
        ),
        migrations.AddField(
            model_name='facttype',
            name='facCobrar',
            field=models.BooleanField(default=False, verbose_name='Factura cobrar'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
