# Generated by Django 3.2.4 on 2021-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0143_auto_20211113_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facttype',
            name='MercPagar',
            field=models.BooleanField(default=False, verbose_name='Mercancia pagar'),
        ),
    ]
