# Generated by Django 3.2.4 on 2021-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0144_alter_facttype_mercpagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttype',
            name='clave',
            field=models.BooleanField(default=False, verbose_name='Tarjeta clave'),
        ),
        migrations.AddField(
            model_name='facttype',
            name='visa',
            field=models.BooleanField(default=False, verbose_name='Tarjeta visa'),
        ),
    ]
