# Generated by Django 3.2.4 on 2021-11-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0145_auto_20211113_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facttype',
            old_name='MercPagada',
            new_name='mercPagada',
        ),
        migrations.RenameField(
            model_name='facttype',
            old_name='MercPagar',
            new_name='mercPagar',
        ),
    ]
