# Generated by Django 3.2.4 on 2021-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0146_auto_20211113_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='facttype',
            name='gasto',
            field=models.BooleanField(default=False, verbose_name='Gasto'),
        ),
        migrations.AddField(
            model_name='facttype',
            name='ingreso',
            field=models.BooleanField(default=False, verbose_name='Ingreso'),
        ),
    ]
