# Generated by Django 3.2.4 on 2021-12-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0147_auto_20211117_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='customTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabNombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre de tabla')),
                ('tabTotal', models.FloatField(verbose_name='Total')),
                ('tabTipo', models.ForeignKey(default='Tipo', on_delete=django.db.models.deletion.CASCADE, to='spareapp.facttype', verbose_name='Tipo')),
            ],
        ),
    ]
