# Generated by Django 3.2.4 on 2021-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0148_customtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtable',
            name='tabNombre',
            field=models.CharField(default='Principal', max_length=20, verbose_name='Nombre de tabla'),
        ),
    ]
