# Generated by Django 3.2.4 on 2021-12-20 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0149_alter_customtable_tabnombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
