# Generated by Django 3.2.4 on 2021-12-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0150_customtable_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtable',
            name='fecha',
        ),
    ]
