# Generated by Django 3.2.4 on 2021-12-22 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0151_remove_customtable_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtable',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='customtable',
            name='printipal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='printipal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='tabNombre',
            field=models.CharField(default='Principal', max_length=20, verbose_name='Nombre de tabla'),
        ),
    ]
