# Generated by Django 3.2.4 on 2021-12-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0152_auto_20211222_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtable',
            old_name='printipal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='maintable',
            old_name='printipal',
            new_name='principal',
        ),
    ]
