# Generated by Django 3.2.4 on 2021-12-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0153_auto_20211222_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='customAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabNombre', models.CharField(default='Principal', max_length=20, verbose_name='Nombre de tabla')),
                ('principal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Principal')),
                ('tabTotal', models.FloatField(verbose_name='Total')),
                ('tabTipo', models.ForeignKey(default='Tipo', on_delete=django.db.models.deletion.CASCADE, to='spareapp.facttype', verbose_name='Tipo')),
            ],
        ),
    ]
