# Generated by Django 3.2.4 on 2021-12-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0154_customaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaux',
            name='tabNombre',
            field=models.CharField(default='Principal', max_length=80, verbose_name='Nombre de tabla'),
        ),
        migrations.AlterField(
            model_name='customtable',
            name='tabNombre',
            field=models.CharField(default='Principal', max_length=80, verbose_name='Nombre de tabla'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='tabNombre',
            field=models.CharField(default='Principal', max_length=80, verbose_name='Nombre de tabla'),
        ),
    ]
