# Generated by Django 4.0.4 on 2022-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0159_factura_nc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='engine_info',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.engine'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_spare',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.spare', verbose_name='Spare target'),
        ),
    ]
