# Generated by Django 4.0.4 on 2022-11-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0160_alter_spare_engine_info_alter_spare_spare_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='gasto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Gasto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ingreso',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ingreso'),
        ),
    ]
