# Generated by Django 4.0.4 on 2023-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0168_alter_spare_spare_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_brand',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
