# Generated by Django 4.0.4 on 2023-05-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0170_alter_spare_spare_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='note',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='VIN'),
        ),
    ]
