# Generated by Django 4.0.4 on 2023-05-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0171_alter_spare_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=40, null=True, verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='car_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.manufacturer', verbose_name='Manufacturer'),
        ),
    ]
