# Generated by Django 4.0.4 on 2023-05-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0173_brand_alter_spare_spare_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brand',
            new_name='branddb',
        ),
    ]
