# Generated by Django 4.0.4 on 2023-05-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0174_rename_brand_branddb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='engine_manufacturer',
        ),
        migrations.AddField(
            model_name='engine',
            name='car_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.manufacturer', verbose_name='Manufacturer'),
        ),
    ]
