# Generated by Django 4.0.4 on 2023-05-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0175_remove_engine_engine_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='car_manufacturer',
            new_name='engine_manufacturer',
        ),
    ]
