# Generated by Django 4.0.4 on 2023-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0176_rename_car_manufacturer_engine_engine_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddb',
            name='brandPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.RemoveField(
            model_name='spare',
            name='spare_brand',
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_brand',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.branddb', verbose_name='Brand'),
        ),
    ]
