# Generated by Django 4.0.4 on 2023-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0177_branddb_brandprice_remove_spare_spare_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='chasis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chasis'),
        ),
    ]
