# Generated by Django 4.0.4 on 2023-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0178_alter_car_chasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_brand',
            field=models.ManyToManyField(blank=True, null=True, to='spareapp.branddb'),
        ),
    ]
