# Generated by Django 4.0.4 on 2023-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0179_alter_spare_spare_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddb',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='branddb',
            name='brandPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
