# Generated by Django 4.0.4 on 2023-08-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0180_branddb_cantidad_alter_branddb_brandprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddb',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.vendor', verbose_name='Vendor'),
        ),
    ]
