# Generated by Django 4.0.4 on 2023-08-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0181_branddb_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddb',
            name='brandPrice',
        ),
        migrations.RemoveField(
            model_name='branddb',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='branddb',
            name='vendor',
        ),
        migrations.CreateModel(
            name='vendorSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandPrice', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('spare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.spare', verbose_name='Spare')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.vendor', verbose_name='Spare')),
            ],
        ),
    ]
