# Generated by Django 4.0.4 on 2023-08-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0182_remove_branddb_brandprice_remove_branddb_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorspare',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.branddb', verbose_name='Brand'),
        ),
    ]
