# Generated by Django 4.0.4 on 2023-08-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0183_vendorspare_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Quantity')),
                ('SubTotal', models.FloatField(blank=True, null=True, verbose_name='SubTotal')),
                ('Total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.vendorspare', verbose_name='Product')),
            ],
        ),
    ]
