# Generated by Django 4.0.4 on 2023-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0184_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='make_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Make group'),
        ),
        migrations.AddField(
            model_name='spare',
            name='model_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model group'),
        ),
    ]
