# Generated by Django 4.0.4 on 2023-09-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0185_spare_make_group_spare_model_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryAtribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute', models.ManyToManyField(blank=True, null=True, to='spareapp.atribute', verbose_name='Atribute')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareapp.category', verbose_name='Category')),
            ],
        ),
    ]
