# Generated by Django 4.0.4 on 2023-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareapp', '0186_categoryatribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryatribute',
            name='atribute',
        ),
        migrations.AddField(
            model_name='categoryatribute',
            name='atribute',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atribute'),
        ),
    ]
